"""Add table

Revision ID: 1c772611a42e
Revises: 
Create Date: 2025-12-14 13:43:05.528445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c772611a42e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('api_id', sa.Integer(), nullable=False),
    sa.Column('api_hash', sa.String(length=64), nullable=False),
    sa.Column('session_string', sa.Text(), nullable=True),
    sa.Column('password_2fa', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'sotilmagan'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_banned', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_accounts_phone_number'), 'telegram_accounts', ['phone_number'], unique=True)
    op.create_index(op.f('ix_telegram_accounts_status'), 'telegram_accounts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_accounts_status'), table_name='telegram_accounts')
    op.drop_index(op.f('ix_telegram_accounts_phone_number'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    # ### end Alembic commands ###
