"""price field

Revision ID: c262d968f15c
Revises: 1c772611a42e
Create Date: 2025-12-14 14:13:20.330640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c262d968f15c'
down_revision: Union[str, Sequence[str], None] = '1c772611a42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('price', sa.Integer(), server_default=sa.text('30'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_accounts', 'price')
    # ### end Alembic commands ###
